baseURL = "https://vformation.netlify.app/"
title = "vFormation"
author = "vFormation"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-SE4TODOTODO"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/vFormation-logo.png"
    alt = "vFormation Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "vFormation"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "vFormation is enhancing business innovation and profitability through strategic consulting"
    meta_og_title = "vFormation - business innovation and profitability"
    meta_og_type = "website"
    meta_og_url = "https://vformation.netlify.app/"
    meta_og_image = "img/logo/vFormation-logo.png"
    meta_og_description = "vFormation is enhancing business innovation and profitability through strategic consulting"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username1"
    meta_twitter_creator = "@username"

[menu]


  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Blog"
    url = "/Blog"
      weight = 2


  [[menu.footer]]
    name = "Contact"
    url = "/Contact"
      weight = 3
